-- attendance.sql

CREATE TABLE public.attendance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id UUID REFERENCES public.employees(user_id),
    branch_id BIGINT REFERENCES public.branches(id),
    clock_in_time TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    clock_out_time TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE public.attendance IS '출퇴근 기록';
COMMENT ON COLUMN public.attendance.employee_id IS '직원 ID';
COMMENT ON COLUMN public.attendance.branch_id IS '지점 ID';
COMMENT ON COLUMN public.attendance.clock_in_time IS '출근 시간';
COMMENT ON COLUMN public.attendance.clock_out_time IS '퇴근 시간';
