-- daily_qrs.sql

CREATE TABLE public.daily_qrs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id BIGINT REFERENCES public.branches(id) NOT NULL,
    qr_data TEXT NOT NULL UNIQUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE public.daily_qrs IS '매일 갱신되는 QR 코드 정보';
COMMENT ON COLUMN public.daily_qrs.branch_id IS '지점 ID';
COMMENT ON COLUMN public.daily_qrs.qr_data IS '날짜마다 바뀌는 고유 QR 값';
COMMENT ON COLUMN public.daily_qrs.created_at IS '생성일';
